### ISSUE TITLE
Web Portal

### ISSUE THREAD

**Issue by Kazuosu** [Kazuosu/Mechanic#3]

**Comment by Kazuosu** [comment]
@Wouter-Vla3 You're going to have to help with this one :P

**Comment by Wouter-Vla3** [comment]
I can imagine. I may be thinking up some ideas :P

**Comment by Kazuosu** [comment]
Haha, Well if you use a nodejs framework would be great and design wise you are the artisit...

**Comment by Wouter-Vla3** [comment]
Hmmm... Nodejs frameworks...

**Comment by Kazuosu** [comment]
Express, angular, vue... im not really into it but you can find one you like probs

**Comment by Kazuosu** [comment]
Well all set, now you take it to the next level ;)

- [ ] Landing 
- [ ] Login for the dash
- [ ] Dashboard

Dash:
- [ ] Stats - Total Messages, Total users...
- [ ] Activity graph?
- [ ] Bot Console output (no need for input)
- [ ] More cool stuff - Nothing concrete right now... would be nice for admins  to manage roles and stuff...

(It's a lot, but all the features you add to the dash I'll have to make a backend for it so yeah...)

**Comment by Kazuosu** [comment]
Somehow integrate exported chats with #18 to the website

**Comment by Kazuosu** [comment]
Closing to assign unique issues to each task, will be easier to work that way,
